### ISSUE TITLE
Problem starting farmplus on paper

### ISSUE THREAD

**Issue by derixithy** [Manuton04/FarmingPlus#1]
I have a problem starting farmplus on my paper 1.20.4 server, i get the following log:

[09:12:45 INFO]: [FarmingPlus] Enabling FarmingPlus v1.1.0
[09:12:45 INFO]: [FarmingPlus] Loaded reward: example1
[09:12:45 INFO]: [FarmingPlus] Loaded reward: example2
[09:12:45 INFO]: [FarmingPlus] Loaded reward: example3
[09:12:45 INFO]: [FarmingPlus] Loaded reward: example4
[09:12:45 INFO]: [FarmingPlus] Loaded reward: example5
[09:12:45 INFO]: [FarmingPlus] Loaded cost: replenish
[09:12:45 INFO]: [FarmingPlus] Loaded cost: farmers-grace
[09:12:45 INFO]: [FarmingPlus] Loaded cost: delicate
[09:12:45 INFO]: [FarmingPlus] Loaded cost: irrigate
[09:12:45 INFO]: [FarmingPlus] Loaded cost: farmers-step1
[09:12:45 INFO]: [FarmingPlus] Loaded cost: farmers-step2
[09:12:45 INFO]: [FarmingPlus] Loaded cost: farmers-step3
[09:12:45 INFO]: [FarmingPlus] Loaded cost: grand-tilling1
[09:12:45 INFO]: [FarmingPlus] Loaded cost: grand-tilling2
[09:12:45 INFO]: [FarmingPlus] Loaded cost: grand-tilling3
[09:12:45 INFO]: [PlaceholderAPI] Successfully registered internal expansion: farmingplus [1.1.0]
[09:12:45 INFO]: ------------------------------------------------
[09:12:45 INFO]: [FarmingPlus] Has been enabled. Version: 1.1.0
[09:12:45 INFO]: ------------------------------------------------
[09:12:45 INFO]: [FarmingPlus] There was an error connecting to the database.
[09:12:45 INFO]: [FarmingPlus] Metrics are enabled.
[09:12:45 ERROR]: Error occurred while enabling FarmingPlus v1.1.0 (Is it up to date?)
java.lang.NoSuchMethodError: 'void org.bukkit.enchantments.Enchantment.<init>(org.bukkit.NamespacedKey)'
	at fp.manuton.enchantments.EnchantmentWrapper.<init>(EnchantmentWrapper.java:15) ~[FarmingPlus-1.1.0.jar:?]
	at fp.manuton.enchantments.CustomEnchantments.<clinit>(CustomEnchantments.java:13) ~[FarmingPlus-1.1.0.jar:?]
	at fp.manuton.FarmingPlus.onEnable(FarmingPlus.java:64) ~[FarmingPlus-1.1.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[purpur-1.20.4.jar:git-Purpur-2118]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2118]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:651) ~[purpur-1.20.4.jar:git-Purpur-2118]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:562) ~[purpur-1.20.4.jar:git-Purpur-2118]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:678) ~[purpur-1.20.4.jar:git-Purpur-2118]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:438) ~[purpur-1.20.4.jar:git-Purpur-2118]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.4.jar:git-Purpur-2118]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1148) ~[purpur-1.20.4.jar:git-Purpur-2118]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.4.jar:git-Purpur-2118]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[09:12:45 INFO]: [FarmingPlus] Disabling FarmingPlus v1.1.0
[09:12:45 INFO]: ------------------------------------------------
[09:12:45 INFO]: [FarmingPlus] Has been disabled. Version: 1.1.0
[09:12:45 INFO]: ------------------------------------------------
[09:12:45 INFO]: [FarmingPlus] Saving rewards records in a JSON...
[09:12:45 INFO]: [FarmingPlus] The rewards records are being saved in a JSON.
[09:12:45 INFO]: [FarmingPlus] The rewards records have been saved.

I checked mysql is disabled (false) in the config, seems to be something with the enchantments function.

Hope you can help resolve this, it seems to be an awesome plugin.

**Comment by Manuton04** [comment]
Ok, thanks for letting me know, I will look into it. You can join the discord server if you want to be in contact.
